# Generated by Django 6.0.2 on 2026-02-27 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RESOLU', 'Résolu')], default='EN_ATTENTE', max_length=20)),
                ('date_attribution', models.DateTimeField(blank=True, null=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requetes_emises', to=settings.AUTH_USER_MODEL)),
                ('division_attribuee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requetes', to='comptes.division')),
                ('service_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requetes_recues', to='comptes.service')),
            ],
            options={
                'verbose_name': 'Requête',
                'verbose_name_plural': 'Requêtes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.TextField()),
                ('intervention_resolue', models.BooleanField(default=False)),
                ('pieces_jointes', models.FileField(blank=True, null=True, upload_to='comptes_rendus/')),
                ('chef_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_rendus', to='requetes.requete')),
            ],
            options={
                'verbose_name': 'Compte rendu',
                'verbose_name_plural': 'Comptes rendus',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('chef_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions_recues', to=settings.AUTH_USER_MODEL)),
                ('chef_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions_effectuees', to=settings.AUTH_USER_MODEL)),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='requetes.requete')),
            ],
            options={
                'verbose_name': 'Attribution',
                'verbose_name_plural': 'Attributions',
            },
        ),
        migrations.CreateModel(
            name='TypeDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('service_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_demande', to='comptes.service')),
            ],
            options={
                'verbose_name': 'Type de demande',
                'verbose_name_plural': 'Types de demande',
            },
        ),
        migrations.AddField(
            model_name='requete',
            name='type_demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requetes', to='requetes.typedemande'),
        ),
    ]
