# Generated by Django 6.0.2 on 2026-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requetes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requete',
            name='priorite',
            field=models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute')], default='normale', max_length=10),
        ),
    ]
