# Generated by Django 6.0.2 on 2026-03-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requetes', '0002_requete_priorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requete',
            name='priorite',
            field=models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=20),
        ),
    ]
