# Generated by Django 6.0.2 on 2026-03-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requetes', '0003_alter_requete_priorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requete',
            name='statut',
            field=models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='EN_ATTENTE', max_length=20),
        ),
    ]
