# Generated by Django 6.0.2 on 2026-03-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requetes', '0004_alter_requete_statut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typedemande',
            options={'ordering': ['nom'], 'verbose_name': 'Type de demande', 'verbose_name_plural': 'Types de demande'},
        ),
        migrations.RemoveField(
            model_name='requete',
            name='priorite',
        ),
        migrations.AlterField(
            model_name='requete',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RESOLU', 'Résolu')], default='EN_ATTENTE', max_length=20),
        ),
    ]
