# Generated by Django 6.0.2 on 2026-03-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requetes', '0005_alter_typedemande_options_remove_requete_priorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requete',
            name='statut_compte_rendu',
            field=models.CharField(choices=[('AUCUN', 'Aucun compte rendu'), ('EN_COURS', 'Compte rendu en cours'), ('RESOLU', 'Compte rendu résolu')], default='AUCUN', max_length=20),
        ),
    ]
