# Generated by Django 6.0.2 on 2026-03-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requetes', '0006_requete_statut_compte_rendu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requete',
            name='statut_compte_rendu',
            field=models.CharField(choices=[('AUCUN', 'Aucun compte rendu'), ('EN_COURS', 'Compte rendu en cours'), ('MODIFIE', 'Compte rendu modifié'), ('RESOLU', 'Compte rendu résolu')], default='AUCUN', max_length=20),
        ),
    ]
