# Generated by Django 6.0.2 on 2026-03-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requetes', '0007_alter_requete_statut_compte_rendu'),
    ]

    operations = [
        migrations.AddField(
            model_name='compterendu',
            name='date_derniere_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
