# Generated by Django 6.0.2 on 2026-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('personnel', 'Personnel'), ('chef_service', 'Chef de service'), ('chef_division', 'Chef de division'), ('directeur', 'Directeur')], default='personnel', max_length=20),
        ),
    ]
