# Generated by Django 6.0.2 on 2026-04-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_utilisateur_notification_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email_is_invalid',
            field=models.BooleanField(default=False, help_text="Indique si l'adresse email a causé un bounce."),
        ),
    ]
